name: Postman Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '40 19 * * *'
  
jobs:
  postman-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Newman and HTML reporter 
        run: npm install -g newman newman-reporter-html

      - name: Run Newman tests
        run: |
          newman --version
          newman run uploading.postman_collection.json \
            --iteration-data uploading-data.json \
            --reporters cli,html \
            --reporter-html-export report.html

      - name: Upload test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: newman-report
          path: report.html
